config/routes.rb
Rails.application.routes.draw do
  resources :scumbags, only: [:index, :show]
  resources :branches, only: [:show, :index]
  resources :cart, only: [:create, :index, :update, :destroy]

  resources :users, only: [:create, :new, :show]
  resources :orders, only: [:index, :show, :create]

  namespace :admin do
   resources :scumbags, only: [:create, :destroy, :new, :index]
   resources :orders, only: [:index, :update]
   get '/dashboard', to: 'base#show'
   resources :users, only: [:update, :edit]
  end

  root :to => "branches#index"
  get '/dashboard', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/:category_slug', to: "branches#show"
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def items
    @contents.map do |scumbag_id, quantity|
      scumbag = Scumbag.find(scumbag_id)
      CartItem.new(scumbag, quantity)
    end
  end

  def items_total
    return 0 if items.empty?
    items.map do |cart_item|
      cart_item.scumbag.price * cart_item.quantity.to_i
    end.reduce(:+)
  end

  def delete_scumbag(id)
    contents.delete(id)
  end

  def total_count
    contents.values.sum
  end

  def add_item(scumbag_id)
    contents[scumbag_id.to_s] ||= 0
    contents[scumbag_id.to_s] += 1
  end

  def count_of(scumbag_id)
    contents[scumbag_id.to_s]
  end

  def update_quantity(cart_params)
    @contents[cart_params[:scumbag_id]] = cart_params[:quantity].to_i
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @cart_items = @cart.items
  end

  def create
    scumbag = Scumbag.find(params[:scumbag_id])

    @cart.add_item(scumbag.id)
    session[:cart] = @cart.contents

    flash[:notice] = "Added #{scumbag.name} to cart."
    redirect_to request.referrer
  end

  def update

    @cart.update_quantity(params[:qty_update])
    session[:cart] = @cart.contents
    redirect_to cart_index_path
  end

  def destroy
    @cart.delete_scumbag(params[:id])
    scumbag = Scumbag.find(params[:id])
    session[:cart] = @cart.contents
    flash[:success] = "Successfully removed the scumbag known as #{view_context.link_to scumbag.name, scumbag_path(scumbag) }!"
    redirect_to cart_index_path
  end

end

app/views/cart/index.html.erb
<div class="jumbotron">
    <div class="container scumbag-cart-item">
      <div class="row">
        <div class="col-xs-2">
        </div>
        <div class="col-xs-2">
          <h3>Scumbag</h3>
        </div>
        <div class="col-xs-2">
            <h3>Price</h3>
        </div>

        <div class="col-xs-2">
            <h3>Quantity</h3>
        </div>

        <div class="col-xs-2">
            <h3>Sub Total</h3>
        </div>
      </div>

  <div class="line-separator"></div>
  <% @cart_items.each do |cart_item| %>

    <div class="row">

      <div class="col-xs-2" id="cart-img">
        <%= image_tag(cart_item.scumbag.image_path, size: "75", class: "cart-thumb") %>
      </div>

      <div class="col-xs-2">
        <%= link_to cart_item.scumbag.name, scumbag_path(cart_item.scumbag) %> <%= "#{cart_item.scumbag.party_abbreviation}" %><br>
        <%= "#{cart_item.scumbag.branch.name}"%>
      </div>

      <div class="col-xs-2">
          <%= "$#{cart_item.scumbag.price}" %>
      </div>

      <div class="col-xs-2">
        <%= form_for(:qty_update, url: cart_path(cart_item.scumbag.id), method: :put, id: "qty") do |f| %>
          <%= f.hidden_field :scumbag_id, value: cart_item.scumbag.id %>
          <%= f.select :quantity, (1..20), {:selected => cart_item.quantity}, {:onChange => 'this.form.submit();' } %>
        <% end %>
      </div>

      <div class="col-xs-2">
          <%= "$#{cart_item.subtotal}" %>
      </div>


      <div class="col-xs-2">
          <%=button_to "Remove", cart_path(cart_item.scumbag.id), class:"btn-xs btn-danger", method: :delete%>
      </div>

    </div>
  <%end %>
    <div class="line-separator"></div>
    <h3>Total: $<%=@cart.items_total %> </h3>
    <% if logged_in? %>
      <%= button_to "Checkout", orders_path, class: "checkout-btn btn btn-primary"%>
    <% else %>
      <p class="login-or-create"><%="#{link_to "Login", login_path} or #{link_to "Create Account to Checkout", new_user_path}".html_safe %></p>
    <%end%>
  </div>
</div>