config/routes.rb
Rails.application.routes.draw do
  resources :scumbags, only: [:index, :show]
  resources :branches, only: [:show, :index]
  resources :cart, only: [:create, :index, :update, :destroy]

  resources :users, only: [:create, :new, :show]
  resources :orders, only: [:index, :show, :create]

  namespace :admin do
   resources :scumbags, only: [:create, :destroy, :new, :index]
   resources :orders, only: [:index, :update]
   get '/dashboard', to: 'base#show'
   resources :users, only: [:update, :edit]
  end

  root :to => "branches#index"
  get '/dashboard', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/:category_slug', to: "branches#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  before_validation :generate_slug

  validates :name, uniqueness: true,
                   presence: true

  validates_presence_of :slug

  has_many :scumbags

  def to_param
    slug
  end

  def self.find(input)
    if input.to_i != 0
      super
    else
      find_by_slug(input)
    end
  end

  def generate_slug
    self.slug = name.parameterize
  end
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def items
    @contents.map do |scumbag_id, quantity|
      scumbag = Scumbag.find(scumbag_id)
      CartItem.new(scumbag, quantity)
    end
  end

  def items_total
    return 0 if items.empty?
    items.map do |cart_item|
      cart_item.scumbag.price * cart_item.quantity.to_i
    end.reduce(:+)
  end

  def delete_scumbag(id)
    contents.delete(id)
  end

  def total_count
    contents.values.sum
  end

  def add_item(scumbag_id)
    contents[scumbag_id.to_s] ||= 0
    contents[scumbag_id.to_s] += 1
  end

  def count_of(scumbag_id)
    contents[scumbag_id.to_s]
  end

  def update_quantity(cart_params)
    @contents[cart_params[:scumbag_id]] = cart_params[:quantity].to_i
  end

end

app/models/cart_item.rb
class CartItem

  attr_reader :scumbag, :quantity

  def initialize(scumbag, quantity)
    @scumbag = scumbag
    @quantity = quantity
  end

  def subtotal
    scumbag.price * quantity.to_i
  end

end

app/models/deed.rb
class Deed < ActiveRecord::Base
  validates :name,       presence: true
  has_many :scumbag_deeds
  has_many :scumbags, through: :scumbag_deeds
end

app/models/order.rb
class Order < ApplicationRecord
  validates :total_price, presence: true
  belongs_to :user
  has_many :scumbag_orders
  has_many :scumbags, through: :scumbag_orders

  enum status: %w(ordered paid cancelled completed)

  def format_created_date
    split_date = created_at.strftime("%A-%d-%B-%Y-%I-%M-%p").split('-')
      """
      #{split_date[0]} the #{split_date[1].to_i.ordinalize},
      #{split_date[2]} #{split_date[3]} at
      #{split_date[4]}:#{split_date[5]} #{split_date[6]}
      """
  end

  def add_items_to_order(cart)
    cart.contents.each do |scumbag_id, quantity|
      scumbag = Scumbag.find(scumbag_id.to_i)
      self.scumbag_orders.create(scumbag_id: scumbag.id,
                                   scumbag_quantity: quantity,
                                   scumbag_price: scumbag.price)
    end
  end

  def self.statuses
    group(:status).count
  end

  # def total #use cart total at time of creating order instead
  #   scumbag_orders.map do |scumbag_order|
  #     scumbag_order.subtotal
  #   end.reduce(:+)
  # end

end

app/models/party.rb
class Party < ActiveRecord::Base
  validates :name, uniqueness:true,
                   presence: true

  has_many :scumbags
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :title,       presence: true
  validates :body,       presence: true
  has_many :scumbag_reviews
  has_many :scumbags, through: :scumbag_reviews
end

app/models/scumbag.rb
class Scumbag < ActiveRecord::Base
  validates :name,       presence: true,
                         uniqueness: true

  validates :price,      presence: true
  validates :image_path, presence: true
  belongs_to :party
  belongs_to :branch
  has_many :scumbag_orders
  has_many :orders, through: :scumbag_orders

  has_many :scumbag_deeds
  has_many :deeds, through: :scumbag_deeds

  has_many :scumbag_reviews
  has_many :reviews, through: :scumbag_reviews

  enum status: %w(active retired)

  def party_abbreviation
    "(#{party.name[0].upcase})"
  end
end

app/models/scumbag_deed.rb
class ScumbagDeed < ActiveRecord::Base
belongs_to :deed
belongs_to :scumbag
end

app/models/scumbag_order.rb
class ScumbagOrder < ApplicationRecord
  validates :scumbag_quantity, presence: true
  validates :scumbag_price, presence: true

  belongs_to :order
  belongs_to :scumbag

  def scumbag_name
    Scumbag.find(scumbag_id).name
  end

  def subtotal
    scumbag_price * scumbag_quantity
  end
end

app/models/scumbag_review.rb
class ScumbagReview < ActiveRecord::Base
belongs_to :review
belongs_to :scumbag
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness:true

  has_secure_password
  has_many :orders

  enum role: %w(user admin)

  def admin?
    role == "admin"
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  def show
    @branch = Branch.find(params[:category_slug])
    @scumbags = @branch.scumbags
  end

  def index
    @branches = Branch.all
  end

  private

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @cart_items = @cart.items
  end

  def create
    scumbag = Scumbag.find(params[:scumbag_id])

    @cart.add_item(scumbag.id)
    session[:cart] = @cart.contents

    flash[:notice] = "Added #{scumbag.name} to cart."
    redirect_to request.referrer
  end

  def update

    @cart.update_quantity(params[:qty_update])
    session[:cart] = @cart.contents
    redirect_to cart_index_path
  end

  def destroy
    @cart.delete_scumbag(params[:id])
    scumbag = Scumbag.find(params[:id])
    session[:cart] = @cart.contents
    flash[:success] = "Successfully removed the scumbag known as #{view_context.link_to scumbag.name, scumbag_path(scumbag) }!"
    redirect_to cart_index_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    redirect_to login_path if guest?
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id]) if current_user.admin?
    @order = current_user.orders.find(params[:id])
  end

  def create
    if @cart.contents.empty?
      flash[:failure] = "Must Have Items in Cart"
      redirect_to request.referrer
    else
      @order = Order.create(total_price: @cart.items_total, user_id: current_user.id)
      @order.add_items_to_order(@cart)
      reset_cart
      redirect_to orders_path
    end
  end

  private

  def reset_cart
    session[:cart] = {}
  end
end

app/controllers/scumbags_controller.rb
class ScumbagsController < ApplicationController

  def index
    @scumbags = Scumbag.all
  end

  def show
    @scumbag = Scumbag.find(params[:id])
    # @deeds = @scumbag.deeds
    # @reviews = @scumbag.reviews
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Logged in as #{@user.username}"
      redirect_to dashboard_path(user_id: @user.id)
    else
      flash.now[:failure] = @user.errors.full_messages
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>LobbyShop</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render "partials/user_nav" %>
    <% else %>
      <%= render "partials/visitor_nav" %>
    <%end%>

    <div class="jumbotron index-header">
      <div class="container text-center index-words">
        <h1 class="index-text">Lobby Shoppe</h1>      
        <p class="index-text">“When they call the roll in the Senate, the Senators do not know whether to answer 'Present' or 'Not Guilty'.”</p>
        <p class="index-text">-Theodore Roosevelt</p>
      </div>
    </div>
    
    <% flash.each do |type, message| %>
      <% message = [message] if message.class == String %>
        <%= content_tag :div, message.join('<br/>').html_safe, class: "flash-#{type}"%>
    <%end%>
    <%= yield %>
  </body>

</html>

app/views/partials/_grid_scumbag.html.erb
<div class="col-xs-18 col-sm-4 col-md-3">
	<div class="productbox">
		<div class="imgthumb img-responsive">
      <% if scumbag.avatar_file_size %>
        <%= image_tag scumbag.avatar.url, class:"index-img"%>
      <% else%>
      <img src="<%= scumbag.image_path %>", id:"#{scumbag.id}_scumbag", class:"index-img">
      <%end%>
        <div class="middle">
          <div class="detail-button"><%= button_to "View", scumbag_path(scumbag), method: :get, class: "btn btn-success btn-md btn-block" %></div>
        </div>
		</div>
		<div class="caption">
			<h5><%= scumbag.name %> <%= scumbag.party_abbreviation %><span class="pull-right"><%= scumbag.branch.name %></span></h5>
      <b class="finalprice">$<%= scumbag.price %></b>
      <% if scumbag.retired? %>
        <p><%= button_to "Scumbag Retired", cart_index_path(scumbag_id: scumbag.id), class: "btn btn-success btn-md btn-block retired-btn", disabled: true %></p>
      <%else%>
        <p><%= button_to "Add to Cart", cart_index_path(scumbag_id: scumbag.id), class: "btn btn-success btn-md btn-block" %></p>
      <%end%>
    </div>
	</div>
</div>

app/views/partials/_login_form.html.erb
<%= form_for(:session, url: login_path, method: :post) do |f| %>
  <%= f.text_field :username, placeholder: 'Username', id: "username"%>
  <%= f.password_field :password, placeholder: 'Password', id: "password" %>
  <%= f.submit "Login", class: "btn login btn-primary" %>
<%end%>

app/views/partials/_nav_dropdown.html.erb
<li><div class="dropdown hamburger">
  <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-bars fa-2x"></i></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Shop by Branch", branches_path %></li>
    <li><%= link_to "All Politicians", scumbags_path%></li>
    <li><%= link_to "Your Cart", cart_index_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Order History", orders_path %></li>
      <li><%= link_to "My Account", user_path(current_user) %></li>
      <li><%= link_to "Log Out", logout_path, :method => :delete %></li>
    <% end %>
    <% if current_user.admin? %>
      <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>
    <% end %>
  </ul>
</div></li>

app/views/partials/_user_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Lobby Shoppe</a>
    </div>

    <ul class="nav navbar-nav pull-right">
      <li class="welcome-msg">Welcome, <%= current_user.username %></li>
      <%= render "partials/nav_dropdown"%>
      <li><a href="/cart" id="cart"> <span class="fa-stack fa-1x cart"><i class="fa fa-shopping-cart fa-stack-2x"></i><p class="fa-stack-1x cart-quantity"><%=@cart.total_count%></p></span></a></li>
      <li><%=button_to "Logout", logout_path, method: :delete, class:"btn btn-primary"%></li>
    </ul>

  </div>
</nav>

app/views/partials/_visitor_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Lobby Shoppe</a>
    </div>

    <ul class="nav navbar-nav pull-right">
      <li><%= render "partials/login_form" %></li>
      <%= render "partials/nav_dropdown"%>
    <li><a href="/cart" id="cart"> <span class="fa-stack fa-1x cart"><i class="fa fa-shopping-cart fa-stack-2x"></i><p class="fa-stack-1x cart-quantity"><%=@cart.total_count%></p></span></a></li>
        <li><a href="users/new" class="create_account">New? Create an Account</a></li>
    </ul>
  </div>
</nav>