config/routes.rb
Rails.application.routes.draw do
  resources :scumbags, only: [:index, :show]
  resources :branches, only: [:show, :index]
  resources :cart, only: [:create, :index, :update, :destroy]

  resources :users, only: [:create, :new, :show]
  resources :orders, only: [:index, :show, :create]

  namespace :admin do
   resources :scumbags, only: [:create, :destroy, :new, :index]
   resources :orders, only: [:index, :update]
   get '/dashboard', to: 'base#show'
   resources :users, only: [:update, :edit]
  end

  root :to => "branches#index"
  get '/dashboard', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/:category_slug', to: "branches#show"
end

app/models/order.rb
class Order < ApplicationRecord
  validates :total_price, presence: true
  belongs_to :user
  has_many :scumbag_orders
  has_many :scumbags, through: :scumbag_orders

  enum status: %w(ordered paid cancelled completed)

  def format_created_date
    split_date = created_at.strftime("%A-%d-%B-%Y-%I-%M-%p").split('-')
      """
      #{split_date[0]} the #{split_date[1].to_i.ordinalize},
      #{split_date[2]} #{split_date[3]} at
      #{split_date[4]}:#{split_date[5]} #{split_date[6]}
      """
  end

  def add_items_to_order(cart)
    cart.contents.each do |scumbag_id, quantity|
      scumbag = Scumbag.find(scumbag_id.to_i)
      self.scumbag_orders.create(scumbag_id: scumbag.id,
                                   scumbag_quantity: quantity,
                                   scumbag_price: scumbag.price)
    end
  end

  def self.statuses
    group(:status).count
  end

  # def total #use cart total at time of creating order instead
  #   scumbag_orders.map do |scumbag_order|
  #     scumbag_order.subtotal
  #   end.reduce(:+)
  # end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def update
    @order = Order.find(params[:id])
    @order.update(status: params[:status])
    redirect_to request.referrer
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    redirect_to login_path if guest?
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id]) if current_user.admin?
    @order = current_user.orders.find(params[:id])
  end

  def create
    if @cart.contents.empty?
      flash[:failure] = "Must Have Items in Cart"
      redirect_to request.referrer
    else
      @order = Order.create(total_price: @cart.items_total, user_id: current_user.id)
      @order.add_items_to_order(@cart)
      reset_cart
      redirect_to orders_path
    end
  end

  private

  def reset_cart
    session[:cart] = {}
  end
end

app/views/orders/index.html.erb
<h1>Orders for <%= current_user.username %></h1>
  <div class="container scumbag-orders">
    <div class="jumbotron orders">

      <div class="row">
        <div class="col-xs-2">
          <h3>Order Number</h3>
        </div>
        <div class="col-xs-2">
          <h3>Date</h3>
        </div>
        <div class="col-xs-2">
            <h3>Total Price</h3>
        </div>

        <div class="col-xs-2">
            <h3>Status</h3>
        </div>

        <div class="col-xs-2">
          <h3>View</h3>
        </div>
      </div>

  <div class="line-separator"></div>
  <% @orders.each do |order| %>

    <div class="row">

      <div class="col-xs-2 order-id">
        <%= order.id %>
      </div>

      <div class="col-xs-2 order-date">
        <%= order.created_at %>
      </div>

      <div class="col-xs-2 order-price">
          <%= order.total_price %>
      </div>

      <div class="col-xs-2">
        <%= order.status %>
      </div>

      <div class="col-xs-2">
          <%= link_to "View", order_path(order) %>
      </div>

    </div>
  <%end %>
</div>

app/views/orders/show.html.erb
<div class="order-header">
  <h1>Order #<%= @order.id %> on <%=@order.format_created_date%>. </h1>
  <h3 class="order-status">Status: <%= @order.status.capitalize %></h3>
</div>

<div class="container all-stations">

  <div class="panel">
    <div class="panel-heading order-panel"><b>Order Items</b></div>
    <table class="table table-striped table-hover table-condensed">
      <tr>
        <th><div id="station-name-header">Politician</div></th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Sub Total</th>
      </tr>

      <% @order.scumbag_orders.each do |scumbag_order| %>
        <tr>
          <td class="order-scumbag-name"><div class="station-name"><%= link_to "#{scumbag_order.scumbag.name} #{scumbag_order.scumbag.party_abbreviation}", scumbag_path(scumbag_order.scumbag) %></div></td>
          <td class="order-scumbag-price">$<%= scumbag_order.scumbag_price %></td>
          <td class="order-scumbag-quantity"><%= scumbag_order.scumbag_quantity %></td>
          <td class="order-scumbag-subtotal">$<%= scumbag_order.subtotal %></td>
        </tr>
      <% end%>
        <tr>
          <td><div class="total">Total:</div></td>
          <td></td>
          <td></td>
          <td class="order-scumbag-total">$<%= @order.total_price %>
        </tr>
    </table>
  </div>
</div>