config/routes.rb
Rails.application.routes.draw do
  resources :scumbags, only: [:index, :show]
  resources :branches, only: [:show, :index]
  resources :cart, only: [:create, :index, :update, :destroy]

  resources :users, only: [:create, :new, :show]
  resources :orders, only: [:index, :show, :create]

  namespace :admin do
   resources :scumbags, only: [:create, :destroy, :new, :index]
   resources :orders, only: [:index, :update]
   get '/dashboard', to: 'base#show'
   resources :users, only: [:update, :edit]
  end

  root :to => "branches#index"
  get '/dashboard', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/:category_slug', to: "branches#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  before_validation :generate_slug

  validates :name, uniqueness: true,
                   presence: true

  validates_presence_of :slug

  has_many :scumbags

  def to_param
    slug
  end

  def self.find(input)
    if input.to_i != 0
      super
    else
      find_by_slug(input)
    end
  end

  def generate_slug
    self.slug = name.parameterize
  end
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def items
    @contents.map do |scumbag_id, quantity|
      scumbag = Scumbag.find(scumbag_id)
      CartItem.new(scumbag, quantity)
    end
  end

  def items_total
    return 0 if items.empty?
    items.map do |cart_item|
      cart_item.scumbag.price * cart_item.quantity.to_i
    end.reduce(:+)
  end

  def delete_scumbag(id)
    contents.delete(id)
  end

  def total_count
    contents.values.sum
  end

  def add_item(scumbag_id)
    contents[scumbag_id.to_s] ||= 0
    contents[scumbag_id.to_s] += 1
  end

  def count_of(scumbag_id)
    contents[scumbag_id.to_s]
  end

  def update_quantity(cart_params)
    @contents[cart_params[:scumbag_id]] = cart_params[:quantity].to_i
  end

end

app/models/cart_item.rb
class CartItem

  attr_reader :scumbag, :quantity

  def initialize(scumbag, quantity)
    @scumbag = scumbag
    @quantity = quantity
  end

  def subtotal
    scumbag.price * quantity.to_i
  end

end

app/models/deed.rb
class Deed < ActiveRecord::Base
  validates :name,       presence: true
  has_many :scumbag_deeds
  has_many :scumbags, through: :scumbag_deeds
end

app/models/order.rb
class Order < ApplicationRecord
  validates :total_price, presence: true
  belongs_to :user
  has_many :scumbag_orders
  has_many :scumbags, through: :scumbag_orders

  enum status: %w(ordered paid cancelled completed)

  def format_created_date
    split_date = created_at.strftime("%A-%d-%B-%Y-%I-%M-%p").split('-')
      """
      #{split_date[0]} the #{split_date[1].to_i.ordinalize},
      #{split_date[2]} #{split_date[3]} at
      #{split_date[4]}:#{split_date[5]} #{split_date[6]}
      """
  end

  def add_items_to_order(cart)
    cart.contents.each do |scumbag_id, quantity|
      scumbag = Scumbag.find(scumbag_id.to_i)
      self.scumbag_orders.create(scumbag_id: scumbag.id,
                                   scumbag_quantity: quantity,
                                   scumbag_price: scumbag.price)
    end
  end

  def self.statuses
    group(:status).count
  end

  # def total #use cart total at time of creating order instead
  #   scumbag_orders.map do |scumbag_order|
  #     scumbag_order.subtotal
  #   end.reduce(:+)
  # end

end

app/models/party.rb
class Party < ActiveRecord::Base
  validates :name, uniqueness:true,
                   presence: true

  has_many :scumbags
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :title,       presence: true
  validates :body,       presence: true
  has_many :scumbag_reviews
  has_many :scumbags, through: :scumbag_reviews
end

app/models/scumbag.rb
class Scumbag < ActiveRecord::Base
  validates :name,       presence: true,
                         uniqueness: true

  validates :price,      presence: true
  validates :image_path, presence: true
  belongs_to :party
  belongs_to :branch
  has_many :scumbag_orders
  has_many :orders, through: :scumbag_orders

  has_many :scumbag_deeds
  has_many :deeds, through: :scumbag_deeds

  has_many :scumbag_reviews
  has_many :reviews, through: :scumbag_reviews

  enum status: %w(active retired)

  def party_abbreviation
    "(#{party.name[0].upcase})"
  end
end

app/models/scumbag_deed.rb
class ScumbagDeed < ActiveRecord::Base
belongs_to :deed
belongs_to :scumbag
end

app/models/scumbag_order.rb
class ScumbagOrder < ApplicationRecord
  validates :scumbag_quantity, presence: true
  validates :scumbag_price, presence: true

  belongs_to :order
  belongs_to :scumbag

  def scumbag_name
    Scumbag.find(scumbag_id).name
  end

  def subtotal
    scumbag_price * scumbag_quantity
  end
end

app/models/scumbag_review.rb
class ScumbagReview < ActiveRecord::Base
belongs_to :review
belongs_to :scumbag
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness:true

  has_secure_password
  has_many :orders

  enum role: %w(user admin)

  def admin?
    role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def show
    if params[:status]
      @orders = Order.where(status: params[:status]).order(created_at: :desc)
    else
      @orders = Order.order(created_at: :desc)
    end
    @orders_count = Order.all.count
    @statuses = Order.statuses
  end

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  def show
    @branch = Branch.find(params[:category_slug])
    @scumbags = @branch.scumbags
  end

  def index
    @branches = Branch.all
  end

  private

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @cart_items = @cart.items
  end

  def create
    scumbag = Scumbag.find(params[:scumbag_id])

    @cart.add_item(scumbag.id)
    session[:cart] = @cart.contents

    flash[:notice] = "Added #{scumbag.name} to cart."
    redirect_to request.referrer
  end

  def update

    @cart.update_quantity(params[:qty_update])
    session[:cart] = @cart.contents
    redirect_to cart_index_path
  end

  def destroy
    @cart.delete_scumbag(params[:id])
    scumbag = Scumbag.find(params[:id])
    session[:cart] = @cart.contents
    flash[:success] = "Successfully removed the scumbag known as #{view_context.link_to scumbag.name, scumbag_path(scumbag) }!"
    redirect_to cart_index_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    redirect_to login_path if guest?
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id]) if current_user.admin?
    @order = current_user.orders.find(params[:id])
  end

  def create
    if @cart.contents.empty?
      flash[:failure] = "Must Have Items in Cart"
      redirect_to request.referrer
    else
      @order = Order.create(total_price: @cart.items_total, user_id: current_user.id)
      @order.add_items_to_order(@cart)
      reset_cart
      redirect_to orders_path
    end
  end

  private

  def reset_cart
    session[:cart] = {}
  end
end

app/controllers/scumbags_controller.rb
class ScumbagsController < ApplicationController

  def index
    @scumbags = Scumbag.all
  end

  def show
    @scumbag = Scumbag.find(params[:id])
    # @deeds = @scumbag.deeds
    # @reviews = @scumbag.reviews
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Logged in as #{@user.username}"
      redirect_to dashboard_path(user_id: @user.id)
    else
      flash.now[:failure] = @user.errors.full_messages
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/base/show.html.erb
  <div class="container scumbag-cart-item">
    <h1>Admin Dashboard</h1>
    <div class="jumbotron orders">
      <%= button_to "Modify Your Account", edit_admin_user_path(current_user), method: :get, class: "btn btn-success btn-md"%>

      <div class="table-width">
        <div class="row">
          <div class="col-xs-2">
            <p><%= link_to 'Ordered', admin_dashboard_path(status: 'ordered') %></p>
          </div>
          <div class="col-xs-2">
            <p><%= link_to 'Paid', admin_dashboard_path(status: 'paid') %></p>
          </div>
          <div class="col-xs-2">
            <p><%= link_to 'Cancelled', admin_dashboard_path(status: 'cancelled') %></p>
          </div>
          <div class="col-xs-2">
            <p><%= link_to 'Completed', admin_dashboard_path(status: 'completed') %></p>
          </div>
          <div class="col-xs-2">
            <p><%= link_to 'All', admin_dashboard_path %></p>
          </div>
        </div>

        <div class="status-table">
          <div class="row">
            <div class="col-xs-2">
              <p><%= @statuses["ordered"] ?  @statuses["ordered"] : 0%></p>
            </div>
            <div class="col-xs-2">
              <p><%= @statuses["paid"] ?  @statuses["paid"] : 0%></p>
            </div>
            <div class="col-xs-2">
              <p><%= @statuses["cancelled"] ?  @statuses["cancelled"] : 0%></p>
            </div>
            <div class="col-xs-2">
              <p><%= @statuses["completed"] ?  @statuses["completed"] : 0%></p>
            </div>
            <div class="col-xs-2">
              <p><%= @orders_count ?  @orders_count : 0%></p>
            </div>
          </div>
        </div>
      </div>

      <div class="row table-margin">
        <div class="col-xs-2">
          <h3>Order Number</h3>
        </div>
        <div class="col-xs-2">
          <h3>Date</h3>
        </div>
        <div class="col-xs-2">
            <h3>Total Price</h3>
        </div>

        <div class="col-xs-2">
            <h3>Status</h3>
        </div>

        <div class="col-xs-2">
          <h3>View</h3>
        </div>

        <div class="col-xs-2">
          <h3>Update Status</h3>
        </div>
      </div>

  <div class="line-separator"></div>
  <% @orders.each do |order| %>

    <div class="row table-margin">

      <div class="col-xs-2 order-id">
        <%= order.id %>
      </div>

      <div class="col-xs-2 order-date">
        <%= order.created_at %>
      </div>

      <div class="col-xs-2 order-price">
          <%= order.total_price %>
      </div>

      <div class="col-xs-2 order-status">
        <%= order.status %>
      </div>

      <div class="col-xs-2 order-view">
          <%= link_to "View", order_path(order) %>
      </div>

      <div class="col-xs-2 order-update">
        <% if order.ordered? %>
          <%= button_to "Mark as Paid", admin_order_path(order, status: 'paid'), method: :patch %><br/>
          <%= button_to "Cancel", admin_order_path(order, status: 'cancelled'), method: :patch %>
        <% elsif order.paid?%>
          <%= button_to "Cancel", admin_order_path(order, status: 'cancelled'), method: :patch %>
          <%= button_to "Mark as Completed", admin_order_path(order, status: 'completed'), method: :patch %>
        <% end %>
      </div>

    </div>
  <%end %>
</div>